/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.qlkh.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.qlkh.service.persistence.HangTrongKhoPK;

import java.io.Serializable;

/**
 * The base model interface for the HangTrongKho service. Represents a row in the &quot;QLKH_HangTrongKho&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.qlkh.model.impl.HangTrongKhoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.qlkh.model.impl.HangTrongKhoImpl}.
 * </p>
 *
 * @author apple
 * @see HangTrongKho
 * @see com.qlkh.model.impl.HangTrongKhoImpl
 * @see com.qlkh.model.impl.HangTrongKhoModelImpl
 * @generated
 */
public interface HangTrongKhoModel extends BaseModel<HangTrongKho> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hang trong kho model instance should use the {@link HangTrongKho} interface instead.
	 */

	/**
	 * Returns the primary key of this hang trong kho.
	 *
	 * @return the primary key of this hang trong kho
	 */
	public HangTrongKhoPK getPrimaryKey();

	/**
	 * Sets the primary key of this hang trong kho.
	 *
	 * @param primaryKey the primary key of this hang trong kho
	 */
	public void setPrimaryKey(HangTrongKhoPK primaryKey);

	/**
	 * Returns the ma kho of this hang trong kho.
	 *
	 * @return the ma kho of this hang trong kho
	 */
	@AutoEscape
	public String getMaKho();

	/**
	 * Sets the ma kho of this hang trong kho.
	 *
	 * @param MaKho the ma kho of this hang trong kho
	 */
	public void setMaKho(String MaKho);

	/**
	 * Returns the ma hang of this hang trong kho.
	 *
	 * @return the ma hang of this hang trong kho
	 */
	@AutoEscape
	public String getMaHang();

	/**
	 * Sets the ma hang of this hang trong kho.
	 *
	 * @param MaHang the ma hang of this hang trong kho
	 */
	public void setMaHang(String MaHang);

	/**
	 * Returns the so luong of this hang trong kho.
	 *
	 * @return the so luong of this hang trong kho
	 */
	public long getSoLuong();

	/**
	 * Sets the so luong of this hang trong kho.
	 *
	 * @param SoLuong the so luong of this hang trong kho
	 */
	public void setSoLuong(long SoLuong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HangTrongKho hangTrongKho);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HangTrongKho> toCacheModel();

	@Override
	public HangTrongKho toEscapedModel();

	@Override
	public HangTrongKho toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}