/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.qlkh.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the KhoHang service. Represents a row in the &quot;QLKH_KhoHang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.qlkh.model.impl.KhoHangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.qlkh.model.impl.KhoHangImpl}.
 * </p>
 *
 * @author apple
 * @see KhoHang
 * @see com.qlkh.model.impl.KhoHangImpl
 * @see com.qlkh.model.impl.KhoHangModelImpl
 * @generated
 */
public interface KhoHangModel extends BaseModel<KhoHang> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kho hang model instance should use the {@link KhoHang} interface instead.
	 */

	/**
	 * Returns the primary key of this kho hang.
	 *
	 * @return the primary key of this kho hang
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this kho hang.
	 *
	 * @param primaryKey the primary key of this kho hang
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ma kho of this kho hang.
	 *
	 * @return the ma kho of this kho hang
	 */
	@AutoEscape
	public String getMaKho();

	/**
	 * Sets the ma kho of this kho hang.
	 *
	 * @param MaKho the ma kho of this kho hang
	 */
	public void setMaKho(String MaKho);

	/**
	 * Returns the ten kho of this kho hang.
	 *
	 * @return the ten kho of this kho hang
	 */
	@AutoEscape
	public String getTenKho();

	/**
	 * Sets the ten kho of this kho hang.
	 *
	 * @param TenKho the ten kho of this kho hang
	 */
	public void setTenKho(String TenKho);

	/**
	 * Returns the dia diem of this kho hang.
	 *
	 * @return the dia diem of this kho hang
	 */
	@AutoEscape
	public String getDiaDiem();

	/**
	 * Sets the dia diem of this kho hang.
	 *
	 * @param DiaDiem the dia diem of this kho hang
	 */
	public void setDiaDiem(String DiaDiem);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KhoHang khoHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KhoHang> toCacheModel();

	@Override
	public KhoHang toEscapedModel();

	@Override
	public KhoHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}